/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

    
import classes.Cargo;
import classes.Colaborador;
import classes.Dependente;
import classes.Empresa;
import classes.Setor;
import dao.CargoDAO;
import dao.ColaboradorDAO;
import dao.DependenteDAO;
import dao.EmpresaDAO;
import dao.SetorDAO;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.JTableHeader;
import javax.swing.text.MaskFormatter;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import pdf.GerarPDF;
/**
 *
 * @author 1_DEV
 */
public class TelaEmpregador extends javax.swing.JFrame {
//
//    private JButton jButtonCalculaINSS;
//    private JLabel jLabelINSS;
//    private JFormattedTextField jFormattedTextFieldSalCVenc1;
      private int idColab;

    /**
     * Creates new form TelaColaborador
     */
    public TelaEmpregador() {
        initComponents();
        //this.setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
        listarSetores();
        listarCargos();
        
        this.setResizable(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalvarColaborador2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanelSalarioComVencimentos = new javax.swing.JPanel();
        jLabelVt3 = new javax.swing.JLabel();
        jLabelInss3 = new javax.swing.JLabel();
        jLabelFaltas3 = new javax.swing.JLabel();
        jTextFieldFaltas = new javax.swing.JTextField();
        jLabelSalarioLiquido3 = new javax.swing.JLabel();
        jLabelIrrf3 = new javax.swing.JLabel();
        jButtonEditarColaborador2 = new javax.swing.JButton();
        jButtonSalvarDescontos = new javax.swing.JButton();
        jLabelINSS = new javax.swing.JLabel();
        jLabelValeTransporte = new javax.swing.JLabel();
        jLabelIRRF = new javax.swing.JLabel();
        jLabelValorFaltas = new javax.swing.JLabel();
        jLabelFaltas4 = new javax.swing.JLabel();
        jCheckBoxValeTransporte = new javax.swing.JCheckBox();
        jLabelDescontos = new javax.swing.JLabel();
        jLabelVencimentos1 = new javax.swing.JLabel();
        jLabelSalLiquido = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabelSalárioBruto1 = new javax.swing.JLabel();
        jLabelDepenQtds1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldHoraExtra = new javax.swing.JTextField();
        jLabelHefd1 = new javax.swing.JLabel();
        jTextFieldHefd = new javax.swing.JTextField();
        jLabelSalarioCVenc1 = new javax.swing.JLabel();
        jLabelHoraExtra1 = new javax.swing.JLabel();
        jButtonSalvarVencimentos = new javax.swing.JButton();
        jButtonEditarVencimentos = new javax.swing.JButton();
        jLabelDepend = new javax.swing.JLabel();
        jLabelHE = new javax.swing.JLabel();
        jLabelHorasTrabalhadas = new javax.swing.JLabel();
        jLabelHEFD = new javax.swing.JLabel();
        jLabelSalarioBruto = new javax.swing.JLabel();
        jLabelSalárioBruto2 = new javax.swing.JLabel();
        jLabelVencimentos = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabelNomeColaborador = new javax.swing.JLabel();
        jLabelColaborador1 = new javax.swing.JLabel();
        jLabelSetor1 = new javax.swing.JLabel();
        jLabelCargo1 = new javax.swing.JLabel();
        jTextFieldNomeColaborador = new javax.swing.JTextField();
        jButtonSalvarColaborador = new javax.swing.JButton();
        jFormattedTextFieldCPFColb = new javax.swing.JFormattedTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jComboBoxSetor = new javax.swing.JComboBox<>();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabelNomeDepen1 = new javax.swing.JLabel();
        jLabelCpfDepen1 = new javax.swing.JLabel();
        jLabelDataNasc1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDependentes = new javax.swing.JTable();
        jButtonSalvarDepen1 = new javax.swing.JButton();
        jFormattedTextFieldCPFDepend = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNascimento = new javax.swing.JFormattedTextField();
        jTextFieldNomeDependente = new javax.swing.JTextField();
        jLabelAuxilio = new javax.swing.JLabel();
        jLabelCpfDepen2 = new javax.swing.JLabel();
        jButtonPDF = new javax.swing.JButton();

        jButtonSalvarColaborador2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvarColaborador2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvarColaborador2.setText("Salvar");
        jButtonSalvarColaborador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarColaborador2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pesquisar");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Empregador");

        jPanelSalarioComVencimentos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSalarioComVencimentos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserir Descontos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanelSalarioComVencimentos.setForeground(new java.awt.Color(0, 0, 0));

        jLabelVt3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelVt3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelVt3.setText("VT:");

        jLabelInss3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInss3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInss3.setText("INSS:");

        jLabelFaltas3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaltas3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFaltas3.setText("Faltas:");

        jTextFieldFaltas.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFaltas.setForeground(new java.awt.Color(0, 0, 0));

        jLabelSalarioLiquido3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalarioLiquido3.setText("Salário Líquido:");

        jLabelIrrf3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIrrf3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIrrf3.setText("IRRF:");

        jButtonEditarColaborador2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditarColaborador2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditarColaborador2.setText("Editar");
        jButtonEditarColaborador2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditarColaborador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarColaborador2ActionPerformed(evt);
            }
        });

        jButtonSalvarDescontos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvarDescontos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvarDescontos.setText("Salvar");
        jButtonSalvarDescontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarDescontosActionPerformed(evt);
            }
        });

        jLabelINSS.setBackground(new java.awt.Color(255, 255, 255));
        jLabelINSS.setForeground(new java.awt.Color(0, 0, 0));
        jLabelINSS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelValeTransporte.setBackground(new java.awt.Color(255, 255, 255));
        jLabelValeTransporte.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValeTransporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIRRF.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIRRF.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIRRF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelValorFaltas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelValorFaltas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorFaltas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelFaltas4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaltas4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFaltas4.setText("Valor Faltas:");

        jCheckBoxValeTransporte.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxValeTransporte.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxValeTransporte.setText("Validacao");

        jLabelDescontos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDescontos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescontos.setText("Total Descontos:");

        jLabelVencimentos1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelVencimentos1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelVencimentos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSalLiquido.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSalLiquido.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalLiquido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelSalarioComVencimentosLayout = new javax.swing.GroupLayout(jPanelSalarioComVencimentos);
        jPanelSalarioComVencimentos.setLayout(jPanelSalarioComVencimentosLayout);
        jPanelSalarioComVencimentosLayout.setHorizontalGroup(
            jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                        .addComponent(jLabelInss3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                        .addComponent(jLabelVt3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValeTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxValeTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                                .addComponent(jLabelFaltas3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                                .addComponent(jLabelFaltas4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelValorFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                        .addComponent(jLabelIrrf3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIRRF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                        .addComponent(jLabelSalarioLiquido3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                        .addComponent(jButtonEditarColaborador2)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonSalvarDescontos))
                    .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                        .addComponent(jLabelDescontos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVencimentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelSalarioComVencimentosLayout.setVerticalGroup(
            jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelInss3)
                        .addComponent(jLabelFaltas3)
                        .addComponent(jTextFieldFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelValorFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFaltas4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelValeTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                            .addComponent(jLabelVt3)
                            .addGap(6, 6, 6)))
                    .addComponent(jCheckBoxValeTransporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelIrrf3))
                    .addComponent(jLabelIRRF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarColaborador2)
                    .addComponent(jButtonSalvarDescontos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVencimentos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabelDescontos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSalarioComVencimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalLiquido, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addGroup(jPanelSalarioComVencimentosLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabelSalarioLiquido3)))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserir Vencimentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(0, 0, 0));

        jLabelSalárioBruto1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSalárioBruto1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalárioBruto1.setText("Salário Bruto:");

        jLabelDepenQtds1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDepenQtds1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDepenQtds1.setText("Dependentes:");

        jTextFieldHoraExtra.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHoraExtra.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldHoraExtra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldHoraExtra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraExtraActionPerformed(evt);
            }
        });

        jLabelHefd1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHefd1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHefd1.setText("H.E.F.D:");

        jTextFieldHefd.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHefd.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldHefd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSalarioCVenc1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSalarioCVenc1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalarioCVenc1.setText("Total Vencimentos:");

        jLabelHoraExtra1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHoraExtra1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHoraExtra1.setText("Hora Extra:");

        jButtonSalvarVencimentos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvarVencimentos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvarVencimentos.setText("Salvar");
        jButtonSalvarVencimentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvarVencimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarVencimentosActionPerformed(evt);
            }
        });

        jButtonEditarVencimentos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditarVencimentos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditarVencimentos.setText("Editar");
        jButtonEditarVencimentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditarVencimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarVencimentosActionPerformed(evt);
            }
        });

        jLabelDepend.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDepend.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDepend.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelHE.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHE.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelHorasTrabalhadas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHorasTrabalhadas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHorasTrabalhadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelHEFD.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHEFD.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHEFD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSalarioBruto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSalarioBruto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalarioBruto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSalárioBruto2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSalárioBruto2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalárioBruto2.setText("Hrs Normais:");

        jLabelVencimentos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelVencimentos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelVencimentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSalárioBruto1)
                            .addComponent(jLabelSalárioBruto2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelHorasTrabalhadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelHoraExtra1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHoraExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonEditarVencimentos)
                                .addGap(51, 51, 51)
                                .addComponent(jButtonSalvarVencimentos))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabelSalarioCVenc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVencimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabelHefd1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldHefd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHEFD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabelDepenQtds1)
                        .addGap(2, 2, 2)
                        .addComponent(jLabelDepend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSalárioBruto1)
                            .addComponent(jLabelDepenQtds1))
                        .addGap(15, 15, 15)
                        .addComponent(jLabelSalárioBruto2))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDepend, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(jLabelSalarioBruto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHorasTrabalhadas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelHEFD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHefd1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldHefd, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabelHoraExtra1))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelHE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldHoraExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarVencimentos)
                    .addComponent(jButtonEditarVencimentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalarioCVenc1)
                    .addComponent(jLabelVencimentos, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Colaborador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel11.setForeground(new java.awt.Color(0, 0, 0));

        jLabelNomeColaborador.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNomeColaborador.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomeColaborador.setText("Nome:");

        jLabelColaborador1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelColaborador1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelColaborador1.setText("CPF:");

        jLabelSetor1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSetor1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSetor1.setText("Setor:");

        jLabelCargo1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCargo1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCargo1.setText("Cargo:");

        jTextFieldNomeColaborador.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeColaborador.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNomeColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeColaboradorActionPerformed(evt);
            }
        });

        jButtonSalvarColaborador.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvarColaborador.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvarColaborador.setText("Salvar");
        jButtonSalvarColaborador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarColaboradorActionPerformed(evt);
            }
        });

        jFormattedTextFieldCPFColb.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldCPFColb.setForeground(new java.awt.Color(0, 0, 0));
        try {
            jFormattedTextFieldCPFColb.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPFColb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFColbActionPerformed(evt);
            }
        });

        jButtonAdicionar.setText("+");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jComboBoxSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSetorActionPerformed(evt);
            }
        });

        jComboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCargoActionPerformed(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSalvarColaborador)
                .addGap(40, 40, 40))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabelSetor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAdicionar))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabelNomeColaborador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelColaborador1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCPFColb, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabelCargo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeColaborador)
                    .addComponent(jLabelColaborador1)
                    .addComponent(jTextFieldNomeColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCPFColb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSetor1)
                        .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCargo1)
                        .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvarColaborador)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserir Dependentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel10.setForeground(new java.awt.Color(0, 0, 0));

        jLabelNomeDepen1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNomeDepen1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomeDepen1.setText("Nome:");

        jLabelCpfDepen1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCpfDepen1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCpfDepen1.setText("CPF:");

        jLabelDataNasc1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDataNasc1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDataNasc1.setText("Data Nasc:");

        jTableDependentes.setAutoCreateRowSorter(true);
        jTableDependentes.setBackground(new java.awt.Color(255, 255, 255));
        jTableDependentes.setForeground(new java.awt.Color(0, 0, 0));
        jTableDependentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Data Nasc", "ID"
            }
        ));
        jTableDependentes.setFocusCycleRoot(true);
        jTableDependentes.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTableDependentes);

        jButtonSalvarDepen1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvarDepen1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvarDepen1.setText("Salvar");
        jButtonSalvarDepen1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvarDepen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarDepen1ActionPerformed(evt);
            }
        });

        jFormattedTextFieldCPFDepend.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldCPFDepend.setForeground(new java.awt.Color(0, 0, 0));
        try {
            jFormattedTextFieldCPFDepend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPFDepend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFDependActionPerformed(evt);
            }
        });

        jFormattedTextFieldDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldDataNascimento.setForeground(new java.awt.Color(0, 0, 0));
        try {
            jFormattedTextFieldDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataNascimentoActionPerformed(evt);
            }
        });

        jTextFieldNomeDependente.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeDependente.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNomeDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeDependenteActionPerformed(evt);
            }
        });

        jLabelAuxilio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAuxilio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAuxilio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCpfDepen2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCpfDepen2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCpfDepen2.setText("Valor Auxilio:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jButtonSalvarDepen1))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabelNomeDepen1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNomeDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(71, 71, 71)
                                .addComponent(jLabelCpfDepen1))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabelDataNasc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCpfDepen2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAuxilio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCPFDepend, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeDepen1)
                    .addComponent(jLabelCpfDepen1)
                    .addComponent(jFormattedTextFieldCPFDepend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDataNasc1)
                        .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCpfDepen2))
                    .addComponent(jLabelAuxilio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButtonSalvarDepen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jButtonPDF.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPDF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonPDF.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPDF.setText("Imprimir");
        jButtonPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSalarioComVencimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButtonVoltar)
                                .addGap(84, 84, 84)
                                .addComponent(jButtonPDF)
                                .addGap(10, 10, 10))
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVoltar)
                            .addComponent(jButtonPDF))
                        .addGap(28, 28, 28)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSalarioComVencimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeColaboradorActionPerformed

    private void jButtonSalvarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarColaboradorActionPerformed
        String nome = jTextFieldNomeColaborador.getText();
        String cpf = jFormattedTextFieldCPFColb.getText();
        String setor = jComboBoxSetor.getSelectedItem().toString().split("-")[0];
        int idSetor = Integer.parseInt(setor);
        String cargo = jComboBoxCargo.getSelectedItem().toString().split("-")[0];
        int idCargo = Integer.parseInt(cargo);
        
         Connection conn = null;
       
        try {
            
            conn = (Connection) DriverManager.getConnection("jdbc:sqlite:src/data/folha_pagamento.db");
            
            SetorDAO setDAO = new SetorDAO(conn); 
            Setor set = new Setor(idSetor, setor);
            setDAO.inserir(set);
            
//            CargoDAO carDAO = new CargoDAO(conn); 
//            Cargo car = new Cargo(cargo, s, b);
//            carDAO.inserir(car);
            
            ColaboradorDAO colabDAO = new ColaboradorDAO(conn);
            Colaborador colab = new Colaborador(nome, cpf, idCargo, idSetor);
            this.idColab=colabDAO.inserir(colab);

            JOptionPane.showMessageDialog(this, "Colaborador salvo com sucesso!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar colaborador.");
        }
        
        
    }//GEN-LAST:event_jButtonSalvarColaboradorActionPerformed

    private void jButtonSalvarColaborador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarColaborador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarColaborador2ActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
       TelaLogin telaEmpregador= new TelaLogin();
            telaEmpregador.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_jButtonVoltarActionPerformed
    
    int nextId = 1; 
    
    private void jButtonSalvarDepen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarDepen1ActionPerformed
        customizeTableHeader();
        
        // Gerar automaticamente o ID
        String id = String.valueOf(nextId);
        
        // Incrementar o próximo ID
        nextId++;
                   
         // Pegar os dados dos JTextFields
        String nome = jTextFieldNomeDependente.getText();
        String cpf = jFormattedTextFieldCPFDepend.getText();
        String dataNascimento = jTextFieldNomeDependente.getText();
        

        // Verificar se todos os campos estão preenchidos
        if ( nome.isEmpty() || cpf.isEmpty() || dataNascimento.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.");
            return;
        }

         Connection conn = null;
       
        try {
            
            conn = (Connection) DriverManager.getConnection("jdbc:sqlite:src/data/folha_pagamento.db");
            
            DependenteDAO dependenteDAO= new DependenteDAO(conn); 
            Dependente dependente = new Dependente(nome, cpf, dataNascimento, this.idColab);
            dependenteDAO.inserir(dependente);
            
            JOptionPane.showMessageDialog(this, "Colaborador salvo com sucesso!");
            
            // Adicionar os dados na tabela
            DefaultTableModel tableModel = (DefaultTableModel) jTableDependentes.getModel();
            tableModel.addRow(new Object[]{nome, cpf, dataNascimento, id});

            // Limpar os campos após a inserção
            jTextFieldNomeDependente.setText("");
            jFormattedTextFieldCPFDepend.setText("");
            jFormattedTextFieldDataNascimento.setText("");

            JOptionPane.showMessageDialog(null, "Dependente salvo com sucesso!");

            // Formatar o valor para exibir a quantidade de dependentes no JLabel
            int quantidadeDependentes = getQuantidadeDependentes();
            DecimalFormat df = new DecimalFormat("##");
            jLabelDepend.setText( df.format(quantidadeDependentes));
            
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar colaborador.");
        }
       
    }//GEN-LAST:event_jButtonSalvarDepen1ActionPerformed
   
    private void jButtonEditarVencimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarVencimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarVencimentosActionPerformed

    private void jButtonSalvarVencimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarVencimentosActionPerformed

        calcularHorasExtras();

        //removendo "R$" e formatando corretamente
        
        double valorHE = Double.parseDouble(jLabelHE.getText().replace(",", "."));
        double valorHEFD = Double.parseDouble(jLabelHEFD.getText().replace(",", "."));

        //Calcular valor total dos vencimentos
        double Vencimentos = valorHE + valorHEFD;

        // Formatar o valor como moeda e exibir
        DecimalFormat df = new DecimalFormat("R$ ##,##0.00");
        jLabelVencimentos.setText(df.format(Vencimentos));
    }//GEN-LAST:event_jButtonSalvarVencimentosActionPerformed

    private void jButtonEditarColaborador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarColaborador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarColaborador2ActionPerformed

    private int getQuantidadeDependentes() {
    DefaultTableModel tableModel = (DefaultTableModel) jTableDependentes.getModel();
    return tableModel.getRowCount(); // Retorna a quantidade de linhas (dependentes) na tabela
    }
    

    private void jButtonSalvarDescontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarDescontosActionPerformed
    String textoVencimento =jLabelSalarioBruto.getText();
        
    try {
        double salario = Double.parseDouble(textoVencimento);
        int dependentes = getQuantidadeDependentes();  // Obtenha o número de dependentes do método
        
        // Cálculo do INSS
        double aliquotaINSS = 0;
        double parcelaDeduzirINSS = 0;

        if (salario <= 1412.00) {
            aliquotaINSS = 0.075;
            parcelaDeduzirINSS = 0;
        } else if (salario <= 2666.68) {
            aliquotaINSS = 0.09;
            parcelaDeduzirINSS = 21.18;
        } else if (salario <= 4000.03) {
            aliquotaINSS = 0.12;
            parcelaDeduzirINSS = 101.18;
        } else if (salario <= 7786.02) {
            aliquotaINSS = 0.14;
            parcelaDeduzirINSS = 181.18;
        }

        double descontoINSS = (salario * aliquotaINSS) - parcelaDeduzirINSS;
        
         // Cálculo do Vale Transporte - Verificar se o colaborador optou por receber o vale
        double descontoValeTransporte = 0;
        if (jCheckBoxValeTransporte.isSelected()) {  // Se o checkbox estiver marcado
            descontoValeTransporte = salario * 0.06; // Aplica o desconto de 6%
        }
        
        // Cálculo da Base de Cálculo do IRRF
        double deducaoDependentes = dependentes * 189.59;
        double baseCalculoIRRF = salario - descontoINSS - deducaoDependentes;

        // Cálculo do IRRF
        double aliquotaIRRF = 0;
        double parcelaDeduzirIRRF = 0;

        if (baseCalculoIRRF <= 2259.20) {
            aliquotaIRRF = 0;
            parcelaDeduzirIRRF = 0;
        } else if (baseCalculoIRRF <= 2826.65) {
            aliquotaIRRF = 0.075;
            parcelaDeduzirIRRF = 169.44;
        } else if (baseCalculoIRRF <= 3751.05) {
            aliquotaIRRF = 0.15;
            parcelaDeduzirIRRF = 381.44;
        } else if (baseCalculoIRRF <= 4664.68) {
            aliquotaIRRF = 0.225;
            parcelaDeduzirIRRF = 662.77;
        } else {
            aliquotaIRRF = 0.275;
            parcelaDeduzirIRRF = 896.00;
        }

        double descontoIRRF = (baseCalculoIRRF * aliquotaIRRF) - parcelaDeduzirIRRF;

        // Formatar o valor para exibir no JLabel
        DecimalFormat df = new DecimalFormat("R$ ##,##0.00");
        jLabelINSS.setText( df.format(descontoINSS));
        jLabelIRRF.setText( df.format(descontoIRRF));
        jLabelValeTransporte.setText( df.format(descontoValeTransporte));

        // Calcular e exibir o valor do auxílio
        double valorAuxilio = calcularAuxilio(salario, dependentes);
        jLabelAuxilio.setText( String.format("%.2f", valorAuxilio));

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Por favor, insira um valor de salário válido.");
    }
    
    // Pegar o salário do colaborador
    double salarioColaborador = Double.parseDouble(jLabelSalarioBruto.getText());

    // Pegar o salário do colaborador
    double dependentes = Double.parseDouble(jLabelDepend.getText());
    
    // Calcular o valor do auxílio com base nos dependentes e salário
    double valorAuxilio = calcularAuxilio(salarioColaborador, (int) dependentes);

    // Exibir o valor do auxílio no JLabel
    jLabelAuxilio.setText("R$" + String.format("%.2f", valorAuxilio));
    
    calcularFaltas();
    
    calcularSalarioLiquido();
    }//GEN-LAST:event_jButtonSalvarDescontosActionPerformed

    private void calcularFaltas() {
    // Obter o salário bruto do JLabel (removendo "R$" e formatando corretamente)
    String salarioBrutoTexto = jLabelSalarioBruto.getText().replace("R$", "").replace(",", ".");
    double salarioBruto = Double.parseDouble(salarioBrutoTexto.trim());

    // Obter a quantidade de faltas do jTextFieldFaltas
    int quantidadeFaltas = Integer.parseInt(jTextFieldFaltas.getText());

    // Calcular o valor de um dia de trabalho (salário bruto dividido por 30 dias)
    double valorDia = salarioBruto / 30;

    // Calcular o valor total das faltas
    double valorFaltas = valorDia * quantidadeFaltas;

    // Exibir o valor das faltas no jLabelValorFaltas, formatado como moeda
    DecimalFormat df = new DecimalFormat("R$ ##,##0.00");
    jLabelValorFaltas.setText(df.format(valorFaltas));
    }
    
    private void calcularSalarioLiquido() {
    // Obter o salário bruto do JLabel (removendo "R$" e formatando corretamente)
    double salarioBruto = Double.parseDouble(jLabelSalarioBruto.getText().replace("R$", "").replace(",", ".").trim());
    
    // Obter os descontos dos JLabel (INSS, Vale Transporte, IRRF e Faltas, Vencimentos)
    double inss = Double.parseDouble(jLabelINSS.getText().replace("R$", "").replace(",", ".").trim());
    double valeTransporte = Double.parseDouble(jLabelValeTransporte.getText().replace("R$", "").replace(",", ".").trim());
    double irrf = Double.parseDouble(jLabelIRRF.getText().replace("R$", "").replace(",", ".").trim());
    double valorFaltas = Double.parseDouble(jLabelValorFaltas.getText().replace("R$", "").replace(",", ".").trim());
    double vencimentos = Double.parseDouble(jLabelValorFaltas.getText().replace("R$", "").replace(",", ".").trim());

    // Somar todos os descontos
    double descontos = inss + valeTransporte + irrf + valorFaltas;
    
    // Calcular o salário líquido
    double salarioLiquido = salarioBruto - descontos + vencimentos;

    // Exibir o resultado no JLabel de vencimentos
    jLabelVencimentos.setText(String.format("R$ %.2f", salarioLiquido));
    // Exibir o resultado no JLabel de descontos
    jLabelDescontos.setText("R$" + String.format("%.2f", descontos));
    }


    
    private double calcularAuxilio(double salario, int quantidadeDependentes) {
    double salarioLimite = 1819.26;
    double valorAuxilioPorDependente = 62.04;

    if (salario <= salarioLimite) {
        return quantidadeDependentes * valorAuxilioPorDependente;
    } else {
        return 0; // Sem direito ao auxílio se o salário for maior que o limite
    }
    }
    private void jTextFieldNomeDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeDependenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeDependenteActionPerformed

    private void jFormattedTextFieldCPFDependActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFDependActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFDependActionPerformed

    private void jFormattedTextFieldCPFColbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFColbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFColbActionPerformed

    private void jFormattedTextFieldDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataNascimentoActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        String setor = JOptionPane.showInputDialog(this, "Insira o setor");
        
        Connection conn = null;
        try {
        // Conecte ao banco de dados
        conn = (Connection) DriverManager.getConnection("jdbc:sqlite:src/data/folha_pagamento.db");
        SetorDAO setDAO = new SetorDAO(conn);

        // Crie o usuário
        Setor set = new Setor(setor);

        // Salve no banco de dados
        setDAO.inserir(set);

        // Mostre mensagem de sucesso
        JOptionPane.showMessageDialog(null, "Setor salvo com sucesso!");
        
        listarSetores();
        
        } catch (Exception e) {          
           JOptionPane.showMessageDialog(null, "Erro ao salvar setor", "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (conn != null) {
                conn.close();
            }
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       


    }//GEN-LAST:event_jButtonAdicionarActionPerformed
    private void listarSetores(){
     // Limpa o JComboBox antes de adicionar os itens
     jComboBoxSetor.removeAllItems();
     
     Connection conn = null;
     try {
       // Conecte ao banco de dados
       conn = (Connection) DriverManager.getConnection("jdbc:sqlite:src/data/folha_pagamento.db");
       SetorDAO setDAO = new SetorDAO(conn);
       
       // Adiciona cada item no JComboBox
        for (Setor setor : setDAO.listarSetores()) {
          String nomeSetor = String.valueOf(setor.getIdSetor()).concat("-").concat(setor.getSetor());
          jComboBoxSetor.addItem(nomeSetor);
        }

     }catch (Exception e) {          
           JOptionPane.showMessageDialog(null, "Erro ao salvar setor!", "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (conn != null) {
                conn.close();
            }
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
         }
    
    
    private void jComboBoxSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSetorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cargo = JOptionPane.showInputDialog(this, "Insira o Cargo");
        String salario = JOptionPane.showInputDialog(this, "Insira o Salário");
        String hN = JOptionPane.showInputDialog(this, "Insira as Horas Contriubidas");
        
        Connection conn = null;
        try {
        // Conecte ao banco de dados
        conn = (Connection) DriverManager.getConnection("jdbc:sqlite:src/data/folha_pagamento.db");
        CargoDAO carDAO = new CargoDAO(conn);

        // Crie o usuário
        Cargo car = new Cargo(cargo, salario, hN);
        // Salve no banco de dados
        carDAO.inserir(car);
 

        // Mostre mensagem de sucesso
        JOptionPane.showMessageDialog(null, "Cargo salvo com sucesso!");
        
        jLabelSalarioBruto.setText(salario);
        jLabelSalarioBruto.setText(hN);
        
        listarSetores();
        
        } catch (Exception e) {          
           JOptionPane.showMessageDialog(null, "Erro ao salvar cargo!", "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (conn != null) {
                conn.close();
            }
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCargoActionPerformed
        // TODO add your handling code here:
        int cargoId = Integer.parseInt(jComboBoxCargo.getSelectedItem().toString().split("-")[0]);     
        
        
         Connection conn = null;
        try {
        // Conecte ao banco de dados
        conn = (Connection) DriverManager.getConnection("jdbc:sqlite:src/data/folha_pagamento.db");
        CargoDAO carDAO = new CargoDAO(conn);

        Cargo cargo = carDAO.getItemById(cargoId);
        jLabelSalarioBruto.setText(cargo.getSalBruto());
        jLabelHorasTrabalhadas.setText(cargo.getHoraNormal());
        
        } catch (Exception e) {          
           JOptionPane.showMessageDialog(null, "Erro ao salvar cargo!", "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (conn != null) {
                conn.close();
            }
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        
        
    }//GEN-LAST:event_jComboBoxCargoActionPerformed

    private void jTextFieldHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraExtraActionPerformed

    private void jButtonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFActionPerformed
        Connection conn = null;
        try {
        // Conecte ao banco de dados
        conn = (Connection) DriverManager.getConnection("jdbc:sqlite:src/data/folha_pagamento.db");

        GerarPDF empDAO = new GerarPDF(conn);
        // Salve no banco de dados
        empDAO.gerarFolhaPagamentoPDF();

        // Mostre mensagem de sucesso
        JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso!");
        } catch (Exception e) {          
           JOptionPane.showMessageDialog(null, "Erro ao salvar usuário!", "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (conn != null) {
                conn.close();
            }
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jButtonPDFActionPerformed
    private void calcularHorasExtras() {
    // Obtenha o texto do JLabel, remova "R$" e substitua a vírgula por ponto
    String textoSalario = jLabelSalarioBruto.getText().replace("R$", "").replace(",", ".");
    
    // Agora, converta para double o salário bruto
    double salarioBruto = Double.parseDouble(textoSalario.trim());
    
    // Obtenha o valor das horas trabalhadas do JLabel e converta para int
    int horasTrabalhadas = Integer.parseInt(jLabelHorasTrabalhadas.getText());

    // Calcular o valor da hora normal
    double valorHoraNormal = salarioBruto / horasTrabalhadas;

    // Obtenha o valor das horas extras e feriados dos JTextFields e converta para int
    int horasExtras = Integer.parseInt(jTextFieldHoraExtra.getText());
    int horasFeriado = Integer.parseInt(jTextFieldHefd.getText());

    // Cálculo das horas extras e feriados
    double valorHorasExtras = horasExtras * valorHoraNormal * 1.5; // 50% a mais para horas extras
    double valorHorasFeriado = horasFeriado * valorHoraNormal * 2.0; // 100% a mais para domingos e feriados

    // Exibir apenas os valores numéricos no JLabel
    jLabelHE.setText(String.format("%.2f", valorHorasExtras));
    jLabelHEFD.setText(String.format("%.2f", valorHorasFeriado));
}
    private void listarCargos(){
     // Limpa o JComboBox antes de adicionar os itens
     jComboBoxCargo.removeAllItems();
     
     Connection conn = null;
     try {
       // Conecte ao banco de dados
       conn = (Connection) DriverManager.getConnection("jdbc:sqlite:src/data/folha_pagamento.db");
       CargoDAO carDAO = new CargoDAO(conn);
       
       // Adiciona cada item no JComboBox
        for (Cargo cargo : carDAO.listarCargos()) {
          String nomeSetor = String.valueOf(cargo.getIdCargo()).concat("-").concat(cargo.getCargo());
          jComboBoxCargo.addItem(nomeSetor);
        }

     }catch (Exception e) {          
           JOptionPane.showMessageDialog(null, "Erro ao salvar cargo!", "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (conn != null) {
                conn.close();
            }
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
         }
       private void customizeTableHeader() {
    // Obtém o cabeçalho da jTableDependentes1
    JTableHeader header = jTableDependentes.getTableHeader();

    // Define a cor de fundo do cabeçalho
    header.setBackground(Color.BLUE);

    // Define a cor do texto do cabeçalho
    header.setForeground(Color.WHITE);

    // Opcional: Alterar a fonte do texto no cabeçalho
    header.setFont(new Font("Arial", Font.BOLD, 14));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmpregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmpregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmpregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmpregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmpregador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonEditarColaborador2;
    private javax.swing.JButton jButtonEditarVencimentos;
    private javax.swing.JButton jButtonPDF;
    private javax.swing.JButton jButtonSalvarColaborador;
    private javax.swing.JButton jButtonSalvarColaborador2;
    private javax.swing.JButton jButtonSalvarDepen1;
    private javax.swing.JButton jButtonSalvarDescontos;
    private javax.swing.JButton jButtonSalvarVencimentos;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBoxValeTransporte;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxSetor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPFColb;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPFDepend;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAuxilio;
    private javax.swing.JLabel jLabelCargo1;
    private javax.swing.JLabel jLabelColaborador1;
    private javax.swing.JLabel jLabelCpfDepen1;
    private javax.swing.JLabel jLabelCpfDepen2;
    private javax.swing.JLabel jLabelDataNasc1;
    private javax.swing.JLabel jLabelDepenQtds1;
    private javax.swing.JLabel jLabelDepend;
    private javax.swing.JLabel jLabelDescontos;
    private javax.swing.JLabel jLabelFaltas3;
    private javax.swing.JLabel jLabelFaltas4;
    private javax.swing.JLabel jLabelHE;
    private javax.swing.JLabel jLabelHEFD;
    private javax.swing.JLabel jLabelHefd1;
    private javax.swing.JLabel jLabelHoraExtra1;
    private javax.swing.JLabel jLabelHorasTrabalhadas;
    private javax.swing.JLabel jLabelINSS;
    private javax.swing.JLabel jLabelIRRF;
    private javax.swing.JLabel jLabelInss3;
    private javax.swing.JLabel jLabelIrrf3;
    private javax.swing.JLabel jLabelNomeColaborador;
    private javax.swing.JLabel jLabelNomeDepen1;
    private javax.swing.JLabel jLabelSalLiquido;
    private javax.swing.JLabel jLabelSalarioBruto;
    private javax.swing.JLabel jLabelSalarioCVenc1;
    private javax.swing.JLabel jLabelSalarioLiquido3;
    private javax.swing.JLabel jLabelSalárioBruto1;
    private javax.swing.JLabel jLabelSalárioBruto2;
    private javax.swing.JLabel jLabelSetor1;
    private javax.swing.JLabel jLabelValeTransporte;
    private javax.swing.JLabel jLabelValorFaltas;
    private javax.swing.JLabel jLabelVencimentos;
    private javax.swing.JLabel jLabelVencimentos1;
    private javax.swing.JLabel jLabelVt3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelSalarioComVencimentos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDependentes;
    private javax.swing.JTextField jTextFieldFaltas;
    private javax.swing.JTextField jTextFieldHefd;
    private javax.swing.JTextField jTextFieldHoraExtra;
    private javax.swing.JTextField jTextFieldNomeColaborador;
    private javax.swing.JTextField jTextFieldNomeDependente;
    // End of variables declaration//GEN-END:variables
}
